### ISSUE TITLE
Inserting tile in Plone 5.1 doesn't work

### ISSUE THREAD

**Issue by fredvd** [collective/collective.tiles.advancedstatic#3]
Screen stays black when the overlay with advancedstatic form fields has been filled out and disappears.

Issue already found: the tile.pt template doesn't contain  <html><body> tags which is probbaly required now by mockup for Plone 5.1 . The parseBodyTag function in utils.js from mockup requires the structure now. 

@cekk Any requirements yet to support Plone 5.1 as well? I have no clue yet how to support and add both Plone 5.0 and 5.1 support in this package, but I'll create a pull request for this template change, I don't think it will break 5.0 support.

**Comment by cekk** [comment]
The problem seems to be how mockup works, because i use this tile in several Plone 5.1 with a different tile manager.

btw for me it's ok, as i've replied on the pull-request.

Thanks

**Comment by fredvd** [comment]
You probably mean redturtle.tiles.management. Briljant 'small' tiles manager, just evaluated it. :-)

**Comment by cekk** [comment]
exactly ;)

**Comment by cekk** [comment]
releases a new version
